/*
 * ODIN Fleet API
 *
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = OdinFleet.Client.FileParameter;
using OpenAPIDateConverter = OdinFleet.Client.OpenAPIDateConverter;

namespace OdinFleet.Model
{
    /// <summary>
    /// AppLocationSetting
    /// </summary>
    [DataContract(Name = "AppLocationSetting")]
    public partial class AppLocationSetting : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AppLocationSetting" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AppLocationSetting() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AppLocationSetting" /> class.
        /// </summary>
        /// <param name="id">The id of the app location setting (required).</param>
        /// <param name="name">The name of the app location setting (required).</param>
        /// <param name="appId">The app id of the app location setting (required).</param>
        /// <param name="serverConfigId">The server config id of the app location setting (required).</param>
        /// <param name="numInstances">The number of instances that should run at the specific location (required).</param>
        /// <param name="autoScalerEnabled">Whether the auto scaler is enabled (required).</param>
        /// <param name="autoScalerMin">The minimum number of instances that should run at the specific location.</param>
        /// <param name="autoScalerMax">The maximum number of instances that should run at the specific location.</param>
        /// <param name="placement">The placement to use (required).</param>
        /// <param name="serverConfig">The server config to use.</param>
        public AppLocationSetting(int id = default(int), string name = default(string), int appId = default(int), int serverConfigId = default(int), int numInstances = default(int), bool autoScalerEnabled = default(bool), int autoScalerMin = default(int), int autoScalerMax = default(int), Placement placement = default(Placement), ServerConfig serverConfig = default(ServerConfig))
        {
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for AppLocationSetting and cannot be null");
            }
            this.Name = name;
            this.AppId = appId;
            this.ServerConfigId = serverConfigId;
            this.NumInstances = numInstances;
            this.AutoScalerEnabled = autoScalerEnabled;
            // to ensure "placement" is required (not null)
            if (placement == null)
            {
                throw new ArgumentNullException("placement is a required property for AppLocationSetting and cannot be null");
            }
            this.Placement = placement;
            this.AutoScalerMin = autoScalerMin;
            this.AutoScalerMax = autoScalerMax;
            this.ServerConfig = serverConfig;
        }

        /// <summary>
        /// The id of the app location setting
        /// </summary>
        /// <value>The id of the app location setting</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public int Id { get; set; }

        /// <summary>
        /// The name of the app location setting
        /// </summary>
        /// <value>The name of the app location setting</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The app id of the app location setting
        /// </summary>
        /// <value>The app id of the app location setting</value>
        [DataMember(Name = "appId", IsRequired = true, EmitDefaultValue = true)]
        public int AppId { get; set; }

        /// <summary>
        /// The server config id of the app location setting
        /// </summary>
        /// <value>The server config id of the app location setting</value>
        [DataMember(Name = "serverConfigId", IsRequired = true, EmitDefaultValue = true)]
        public int ServerConfigId { get; set; }

        /// <summary>
        /// The number of instances that should run at the specific location
        /// </summary>
        /// <value>The number of instances that should run at the specific location</value>
        [DataMember(Name = "numInstances", IsRequired = true, EmitDefaultValue = true)]
        public int NumInstances { get; set; }

        /// <summary>
        /// Whether the auto scaler is enabled
        /// </summary>
        /// <value>Whether the auto scaler is enabled</value>
        [DataMember(Name = "autoScalerEnabled", IsRequired = true, EmitDefaultValue = true)]
        public bool AutoScalerEnabled { get; set; }

        /// <summary>
        /// The minimum number of instances that should run at the specific location
        /// </summary>
        /// <value>The minimum number of instances that should run at the specific location</value>
        [DataMember(Name = "autoScalerMin", EmitDefaultValue = false)]
        public int AutoScalerMin { get; set; }

        /// <summary>
        /// The maximum number of instances that should run at the specific location
        /// </summary>
        /// <value>The maximum number of instances that should run at the specific location</value>
        [DataMember(Name = "autoScalerMax", EmitDefaultValue = false)]
        public int AutoScalerMax { get; set; }

        /// <summary>
        /// The placement to use
        /// </summary>
        /// <value>The placement to use</value>
        [DataMember(Name = "placement", IsRequired = true, EmitDefaultValue = true)]
        public Placement Placement { get; set; }

        /// <summary>
        /// The server config to use
        /// </summary>
        /// <value>The server config to use</value>
        [DataMember(Name = "serverConfig", EmitDefaultValue = false)]
        public ServerConfig ServerConfig { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AppLocationSetting {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  AppId: ").Append(AppId).Append("\n");
            sb.Append("  ServerConfigId: ").Append(ServerConfigId).Append("\n");
            sb.Append("  NumInstances: ").Append(NumInstances).Append("\n");
            sb.Append("  AutoScalerEnabled: ").Append(AutoScalerEnabled).Append("\n");
            sb.Append("  AutoScalerMin: ").Append(AutoScalerMin).Append("\n");
            sb.Append("  AutoScalerMax: ").Append(AutoScalerMax).Append("\n");
            sb.Append("  Placement: ").Append(Placement).Append("\n");
            sb.Append("  ServerConfig: ").Append(ServerConfig).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
