/*
 * ODIN Fleet API
 *
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = OdinFleet.Client.FileParameter;
using OpenAPIDateConverter = OdinFleet.Client.OpenAPIDateConverter;

namespace OdinFleet.Model
{
    /// <summary>
    /// ConfigTemplate
    /// </summary>
    [DataContract(Name = "ConfigTemplate")]
    public partial class ConfigTemplate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigTemplate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ConfigTemplate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ConfigTemplate" /> class.
        /// </summary>
        /// <param name="id">The id of the config template (required).</param>
        /// <param name="binaryId">The binary id of the config template (required).</param>
        /// <param name="name">The name of the config template (required).</param>
        /// <param name="content">The path in the container (required).</param>
        public ConfigTemplate(string id = default(string), string binaryId = default(string), string name = default(string), string content = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for ConfigTemplate and cannot be null");
            }
            this.Id = id;
            // to ensure "binaryId" is required (not null)
            if (binaryId == null)
            {
                throw new ArgumentNullException("binaryId is a required property for ConfigTemplate and cannot be null");
            }
            this.BinaryId = binaryId;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for ConfigTemplate and cannot be null");
            }
            this.Name = name;
            // to ensure "content" is required (not null)
            if (content == null)
            {
                throw new ArgumentNullException("content is a required property for ConfigTemplate and cannot be null");
            }
            this.Content = content;
        }

        /// <summary>
        /// The id of the config template
        /// </summary>
        /// <value>The id of the config template</value>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// The binary id of the config template
        /// </summary>
        /// <value>The binary id of the config template</value>
        [DataMember(Name = "binaryId", IsRequired = true, EmitDefaultValue = true)]
        public string BinaryId { get; set; }

        /// <summary>
        /// The name of the config template
        /// </summary>
        /// <value>The name of the config template</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The path in the container
        /// </summary>
        /// <value>The path in the container</value>
        [DataMember(Name = "content", IsRequired = true, EmitDefaultValue = true)]
        public string Content { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConfigTemplate {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  BinaryId: ").Append(BinaryId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
