/*
 * ODIN Fleet API
 *
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = OdinFleet.Client.FileParameter;
using OpenAPIDateConverter = OdinFleet.Client.OpenAPIDateConverter;

namespace OdinFleet.Model
{
    /// <summary>
    /// DockerCompose
    /// </summary>
    [DataContract(Name = "DockerCompose")]
    public partial class DockerCompose : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DockerCompose" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DockerCompose() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DockerCompose" /> class.
        /// </summary>
        /// <param name="composeFile">The content of the docker compose file (required).</param>
        public DockerCompose(string composeFile = default(string))
        {
            // to ensure "composeFile" is required (not null)
            if (composeFile == null)
            {
                throw new ArgumentNullException("composeFile is a required property for DockerCompose and cannot be null");
            }
            this.ComposeFile = composeFile;
        }

        /// <summary>
        /// The content of the docker compose file
        /// </summary>
        /// <value>The content of the docker compose file</value>
        [DataMember(Name = "composeFile", IsRequired = true, EmitDefaultValue = true)]
        public string ComposeFile { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DockerCompose {\n");
            sb.Append("  ComposeFile: ").Append(ComposeFile).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
