/*
 * ODIN Fleet API
 *
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = OdinFleet.Client.FileParameter;
using OpenAPIDateConverter = OdinFleet.Client.OpenAPIDateConverter;

namespace OdinFleet.Model
{
    /// <summary>
    /// Defines EnvironmentVariableType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum EnvironmentVariableType
    {
        /// <summary>
        /// Enum Static for value: static
        /// </summary>
        [EnumMember(Value = "static")]
        Static = 1,

        /// <summary>
        /// Enum System for value: system
        /// </summary>
        [EnumMember(Value = "system")]
        System = 2,

        /// <summary>
        /// Enum Port for value: port
        /// </summary>
        [EnumMember(Value = "port")]
        Port = 3
    }

}
