/*
 * ODIN Fleet API
 *
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = OdinFleet.Client.FileParameter;
using OpenAPIDateConverter = OdinFleet.Client.OpenAPIDateConverter;

namespace OdinFleet.Model
{
    /// <summary>
    /// Mount
    /// </summary>
    [DataContract(Name = "Mount")]
    public partial class Mount : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Mount" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Mount() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Mount" /> class.
        /// </summary>
        /// <param name="target">The path in the container (required).</param>
        /// <param name="varReadOnly">Whether this mount point is read only (required).</param>
        public Mount(string target = default(string), bool varReadOnly = default(bool))
        {
            // to ensure "target" is required (not null)
            if (target == null)
            {
                throw new ArgumentNullException("target is a required property for Mount and cannot be null");
            }
            this.Target = target;
            this.VarReadOnly = varReadOnly;
        }

        /// <summary>
        /// The path in the container
        /// </summary>
        /// <value>The path in the container</value>
        [DataMember(Name = "target", IsRequired = true, EmitDefaultValue = true)]
        public string Target { get; set; }

        /// <summary>
        /// Whether this mount point is read only
        /// </summary>
        /// <value>Whether this mount point is read only</value>
        [DataMember(Name = "readOnly", IsRequired = true, EmitDefaultValue = true)]
        public bool VarReadOnly { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Mount {\n");
            sb.Append("  Target: ").Append(Target).Append("\n");
            sb.Append("  VarReadOnly: ").Append(VarReadOnly).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
