/*
 * ODIN Fleet API
 *
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = OdinFleet.Client.FileParameter;
using OpenAPIDateConverter = OdinFleet.Client.OpenAPIDateConverter;

namespace OdinFleet.Model
{
    /// <summary>
    /// Placement
    /// </summary>
    [DataContract(Name = "Placement")]
    public partial class Placement : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Placement" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Placement() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Placement" /> class.
        /// </summary>
        /// <param name="constraints">The constraints to use (required).</param>
        public Placement(Constraints constraints = default(Constraints))
        {
            // to ensure "constraints" is required (not null)
            if (constraints == null)
            {
                throw new ArgumentNullException("constraints is a required property for Placement and cannot be null");
            }
            this.Constraints = constraints;
        }

        /// <summary>
        /// The constraints to use
        /// </summary>
        /// <value>The constraints to use</value>
        [DataMember(Name = "constraints", IsRequired = true, EmitDefaultValue = true)]
        public Constraints Constraints { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Placement {\n");
            sb.Append("  Constraints: ").Append(Constraints).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
