/*
 * ODIN Fleet API
 *
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = OdinFleet.Client.FileParameter;
using OpenAPIDateConverter = OdinFleet.Client.OpenAPIDateConverter;

namespace OdinFleet.Model
{
    /// <summary>
    /// PortDefinition
    /// </summary>
    [DataContract(Name = "PortDefinition")]
    public partial class PortDefinition : IValidatableObject
    {

        /// <summary>
        /// Defines whether the port uses the hosts network or the ingress network
        /// </summary>
        /// <value>Defines whether the port uses the hosts network or the ingress network</value>
        [DataMember(Name = "publishMode", IsRequired = true, EmitDefaultValue = true)]
        public PublishMode PublishMode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PortDefinition" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PortDefinition() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PortDefinition" /> class.
        /// </summary>
        /// <param name="name">The name of the server config (required).</param>
        /// <param name="protocols">The protocols to expose (required).</param>
        /// <param name="targetPort">The port to expose (required).</param>
        /// <param name="publishMode">Defines whether the port uses the hosts network or the ingress network (required).</param>
        public PortDefinition(string name = default(string), List<Protocol> protocols = default(List<Protocol>), int targetPort = default(int), PublishMode publishMode = default(PublishMode))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for PortDefinition and cannot be null");
            }
            this.Name = name;
            // to ensure "protocols" is required (not null)
            if (protocols == null)
            {
                throw new ArgumentNullException("protocols is a required property for PortDefinition and cannot be null");
            }
            this.Protocols = protocols;
            this.TargetPort = targetPort;
            this.PublishMode = publishMode;
        }

        /// <summary>
        /// The name of the server config
        /// </summary>
        /// <value>The name of the server config</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// The protocols to expose
        /// </summary>
        /// <value>The protocols to expose</value>
        [DataMember(Name = "protocols", IsRequired = true, EmitDefaultValue = true)]
        public List<Protocol> Protocols { get; set; }

        /// <summary>
        /// The port to expose
        /// </summary>
        /// <value>The port to expose</value>
        [DataMember(Name = "targetPort", IsRequired = true, EmitDefaultValue = true)]
        public int TargetPort { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PortDefinition {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Protocols: ").Append(Protocols).Append("\n");
            sb.Append("  TargetPort: ").Append(TargetPort).Append("\n");
            sb.Append("  PublishMode: ").Append(PublishMode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
