/*
 * ODIN Fleet API
 *
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = OdinFleet.Client.FileParameter;
using OpenAPIDateConverter = OdinFleet.Client.OpenAPIDateConverter;

namespace OdinFleet.Model
{
    /// <summary>
    /// Resources
    /// </summary>
    [DataContract(Name = "Resources")]
    public partial class Resources : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Resources" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Resources() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Resources" /> class.
        /// </summary>
        /// <param name="cpu">The amount of cpu to allocate in cores (required).</param>
        /// <param name="memory">The amount of memory to allocate in GB (required).</param>
        public Resources(decimal cpu = default(decimal), decimal memory = default(decimal))
        {
            this.Cpu = cpu;
            this.Memory = memory;
        }

        /// <summary>
        /// The amount of cpu to allocate in cores
        /// </summary>
        /// <value>The amount of cpu to allocate in cores</value>
        [DataMember(Name = "cpu", IsRequired = true, EmitDefaultValue = true)]
        public decimal Cpu { get; set; }

        /// <summary>
        /// The amount of memory to allocate in GB
        /// </summary>
        /// <value>The amount of memory to allocate in GB</value>
        [DataMember(Name = "memory", IsRequired = true, EmitDefaultValue = true)]
        public decimal Memory { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Resources {\n");
            sb.Append("  Cpu: ").Append(Cpu).Append("\n");
            sb.Append("  Memory: ").Append(Memory).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
