/*
 * ODIN Fleet API
 *
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = OdinFleet.Client.FileParameter;
using OpenAPIDateConverter = OdinFleet.Client.OpenAPIDateConverter;

namespace OdinFleet.Model
{
    /// <summary>
    /// ResourceAllocations
    /// </summary>
    [DataContract(Name = "ResourceAllocations")]
    public partial class ResourceAllocations : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceAllocations" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ResourceAllocations() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceAllocations" /> class.
        /// </summary>
        /// <param name="limits">The limits set for the server (required).</param>
        /// <param name="reservations">The resources that are reserved for the server (required).</param>
        public ResourceAllocations(Resources limits = default(Resources), Resources reservations = default(Resources))
        {
            // to ensure "limits" is required (not null)
            if (limits == null)
            {
                throw new ArgumentNullException("limits is a required property for ResourceAllocations and cannot be null");
            }
            this.Limits = limits;
            // to ensure "reservations" is required (not null)
            if (reservations == null)
            {
                throw new ArgumentNullException("reservations is a required property for ResourceAllocations and cannot be null");
            }
            this.Reservations = reservations;
        }

        /// <summary>
        /// The limits set for the server
        /// </summary>
        /// <value>The limits set for the server</value>
        [DataMember(Name = "limits", IsRequired = true, EmitDefaultValue = true)]
        public Resources Limits { get; set; }

        /// <summary>
        /// The resources that are reserved for the server
        /// </summary>
        /// <value>The resources that are reserved for the server</value>
        [DataMember(Name = "reservations", IsRequired = true, EmitDefaultValue = true)]
        public Resources Reservations { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ResourceAllocations {\n");
            sb.Append("  Limits: ").Append(Limits).Append("\n");
            sb.Append("  Reservations: ").Append(Reservations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
