/*
 * ODIN Fleet API
 *
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.
 *
 * The version of the OpenAPI document: 0.8.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = OdinFleet.Client.FileParameter;
using OpenAPIDateConverter = OdinFleet.Client.OpenAPIDateConverter;

namespace OdinFleet.Model
{
    /// <summary>
    /// SteamWorks
    /// </summary>
    [DataContract(Name = "SteamWorks")]
    public partial class SteamWorks : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SteamWorks" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SteamWorks() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SteamWorks" /> class.
        /// </summary>
        /// <param name="steamAppId">The Steam App ID (required).</param>
        /// <param name="branch">The branch to use (required).</param>
        /// <param name="password">The password to use (required).</param>
        public SteamWorks(string steamAppId = default(string), string branch = default(string), string password = default(string))
        {
            // to ensure "steamAppId" is required (not null)
            if (steamAppId == null)
            {
                throw new ArgumentNullException("steamAppId is a required property for SteamWorks and cannot be null");
            }
            this.SteamAppId = steamAppId;
            // to ensure "branch" is required (not null)
            if (branch == null)
            {
                throw new ArgumentNullException("branch is a required property for SteamWorks and cannot be null");
            }
            this.Branch = branch;
            // to ensure "password" is required (not null)
            if (password == null)
            {
                throw new ArgumentNullException("password is a required property for SteamWorks and cannot be null");
            }
            this.Password = password;
        }

        /// <summary>
        /// The Steam App ID
        /// </summary>
        /// <value>The Steam App ID</value>
        [DataMember(Name = "steamAppId", IsRequired = true, EmitDefaultValue = true)]
        public string SteamAppId { get; set; }

        /// <summary>
        /// The branch to use
        /// </summary>
        /// <value>The branch to use</value>
        [DataMember(Name = "branch", IsRequired = true, EmitDefaultValue = true)]
        public string Branch { get; set; }

        /// <summary>
        /// The password to use
        /// </summary>
        /// <value>The password to use</value>
        [DataMember(Name = "password", IsRequired = true, EmitDefaultValue = true)]
        public string Password { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SteamWorks {\n");
            sb.Append("  SteamAppId: ").Append(SteamAppId).Append("\n");
            sb.Append("  Branch: ").Append(Branch).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
